---
title: "**Power and sample size**"
author: ""
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    vertical_layout: fill
    orientation: columns
    source_code: https://github.com/GiankDiluvi/power
    navbar:
      - { title: "Gian Carlo Diluvi", align: right }
runtime: shiny
---

<style type="text/css">

.sidebar {  /* sidebar  */
   font-size: 14px;
   font-family: Helvetica;
   }
.navbar-inverse .navbar{
  font-family: Helvetica;
}
.navbar-inverse .navbar-brand{
  font-family: Helvetica;
  color: #000000;
  pointer-events: none;
}
</style>




```{r global, include=FALSE, warning = FALSE}
# basics
library(flexdashboard)
library(tidyverse)
# plotting
library(ggplot2)
ggplot2::theme_set(theme_classic())
library(patchwork)
library(plotly)
# markdown
library(knitr)
library(kableExtra)
# shiny + html
library(shiny)
withMathJax()
library(shinyWidgets)
library(DT)
library(miniUI)
```


**Density plots**
=====================================

Column {.sidebar}
-------------------------------------

We are testing 
<!--
$$
H_0: \mu = \mu_0 \enspace \mathrm{vs} \enspace H_1: \mu = \mu_1 > \mu_0.
$$
-->
$$
H_0: \mu = \mu_0
$$
against
$$
H_1: \mu = \mu_1 > \mu_0.
$$

<hr>


**Select population parameters:**


```{r h0.params}

sliderInput("mu", label = withMathJax("Null and alternative means \\( \\mu_0, \\mu_1 \\) \n
                                      Select \\( \\mu_0 < \\mu_1 \\):"),
            min = -2, max = 2, value = c(0, 1), step = 0.1)


sliderInput("sigma2", label = withMathJax('Variance \\( \\sigma^2 \\):'),
             min = 0, max = 10, value = 1, step = 0.1)

```


<hr>


**Select test settings:**


```{r h1.params}



# sliderInput("mu1", label = withMathJax('Alternative mean \\( \\mu_1 \\):'),
#             min = 0, max = 2, value = 1, step = 0.1)


numericInput("n", label = withMathJax("Sample size \\( n \\):"),
             min = 3, value = 10, step = 1)

sliderInput("alpha", label = withMathJax('Type I error rate \\( \\alpha \\):'),
            min = 0, max = 1, value = 0.05)

```

<hr>

The effect size $d = (\mu_1 - \mu_0) / \sigma$ is

```{r effect.size}
  
renderPrint({
  # read inputs
   mu <- input$mu
   mu0 <- mu[1]
   mu1 <- mu[2]
  #mu0 <- input$mu0
  #mu1 <- input$mu1
  sigma2 <- input$sigma2
  print(paste0("d = ", round((mu1 - mu0) / sqrt(sigma2), 2)))
})  

```





Column
-------------------------------------


###



```{r plot}

renderPlot({
  
  # read inputs
  mu <- input$mu
  mu0 <- mu[1]
  mu1 <- mu[2]
  #mu0 <- input$mu0
  #mu1 <- input$mu1
  sigma2 <- input$sigma2
  
  n <- input$n
  t1e <- input$alpha
  
  # create params
  sdt <- (n-1) / (n-3)
  tncp <- (mu1 - mu0) * sqrt(n / sigma2)
  
  xmin0 <- qt(0.003, df = n-1)
  xmin1 <- qt(0.003, df = n-1, ncp = tncp)
  xmin <- min(xmin0, xmin1)
  
  xmax0 <- qt(0.997, df = n-1)
  xmax1 <- qt(0.99, df = n-1, ncp = tncp)
  xmax <- max(xmax0, xmax1)
  
  ymax0 <- dt(0, df=n-1)
  ymax1 <- ymax0
  ymax <- max(ymax0, ymax1)
  
  cv0 <- qt(1-t1e, df = n-1)
  
  h0 <- ggplot(tibble(x = c(xmin, xmax)), aes(x)) +
    stat_function(fun = dt, 
                  args = list(df = n-1)) + #adds t density plot
     geom_segment(aes(x = cv0, y = 0, 
                      xend = cv0, yend = 1.15*ymax0),
                  linetype="dashed",
                  size=0.5) + # adds line on critical value
     stat_function(fun = dt, 
                   args = list(df = n-1),
                   xlim = c(xmin, cv0),
                   geom = "area",
                   fill = "#55C667FF") + # fill up specificity
     stat_function(fun = dt, 
                   args = list(df = n-1),
                   xlim = c(cv0, xmax),
                   geom = "area",
                   fill = "#D64B40FF") + # fill up type I error +
     geom_text(aes(label = "alpha",
                   x = cv0 + sdt/4, 
                   y = dt(cv0 + sdt/4, df = n-1) + 0.18*ymax0),
               parse = TRUE,
               size = 4.5) +           # add alpha label
     geom_text(aes(label = as.character(t1e),
                   x = cv0 + sdt/4, 
                   y = dt(cv0 + sdt/4, df = n-1)  + 0.18*ymax0 - 0.1*ymax0),
               parse = TRUE,
               size = 4.5) +           # add alpha value
     # geom_text(aes(label = "Specificity",
     #               x = cv0  - sdt/4, 
     #               y = dt(cv0  - sdt/4, df = n-1) + 0.18*ymax0),
     #           parse = TRUE,
     #           size = 4.5) +           # add specificity label
     # geom_text(aes(label = as.character(1 - t1e),
     #               x = cv0 - sdt/4, 
     #               y = dt(cv0 - sdt/4, df = n-1) + 0.18*ymax0 - 0.06*ymax0),
     #           parse = TRUE,
     #           size = 4.5) +           # add specificity value
     geom_text(aes(label = as.character(round(cv0, 2)),
                   x = cv0, 
                   y = 1.2*ymax0),
               parse = TRUE,
               size = 5) +          # add critical value
     labs(x = "t",
          y = "Density",
          title = expression(paste("     Distribution of test statistic under ", H[0]))) +
    xlim(c(xmin, xmax)) +
    theme(text = element_text(size = 16))
  
  power <- pt(cv0, df = n-1, ncp = tncp, lower.tail = FALSE)
  power_label <- ifelse(round(power, 2) == 1, "NULL>0.99", as.character(round(power, 2)))
  
  
  h1 <- ggplot(tibble(x = c(xmin, xmax)), aes(x)) +
    stat_function(fun = dt, 
                  args = list(df = n-1, ncp = tncp)) + #adds t plot
    geom_segment(aes(x = cv0, y = 0, 
                     xend = cv0, yend = 1.15*ymax1),
                 linetype="dashed",
                 size=0.5) + # adds line on critical value
    stat_function(fun = dt, 
                  args = list(df = n-1, ncp = tncp),
                  xlim = c(xmin, cv0),
                  geom = "area",
                  fill = ifelse(mu0 == mu1, "#55C667FF", "#FCA007FF")) + # fill up  type II error
    stat_function(fun = dt, 
                  args = list(df = n-1, ncp = tncp),
                  xlim = c(cv0, xmax),
                  geom = "area",
                  fill = ifelse(mu0 == mu1, "#D64B40FF", "#39558CFF"),
                  alpha = ifelse(mu0 == mu1, 1, 0.75)) + # fill up power +
    geom_text(aes(label = ifelse(mu0 == mu1, "alpha", "Power"),
                  x = cv0 + sdt/4, 
                  y = dt(cv0 + sdt/4, df = n-1, ncp = tncp) + 0.18*ymax1),
              parse = TRUE,
              size = 4.5) +           # add power label
    annotate("text", 
             x = cv0 + sdt/4,
             y = dt(cv0 + sdt/4, df = n-1, ncp = tncp)  + 0.18*ymax1 - 0.1*ymax1,
             parse = TRUE, 
             label = power_label,
             size = 4.5) +               # add power value
    # geom_text(aes(label = "beta",
    #               x = cv0  - sdt/4,
    #               y = dt(cv0  - sdt/4, df = n-1, ncp = tncp) + 0.18*ymax1),
    #           parse = TRUE,
    #           size = 4.5) +           # add t2e label
    # geom_text(aes(label = as.character(round(1 - power, 2)),
    #               x = cv0 - sdt/4,
    #               y = dt(cv0 - sdt/4, df = n-1, ncp = tncp) + 0.18*ymax1 - 0.06*ymax1),
    #           parse = TRUE,
    #           size = 4.5) +           # add t2e value
    # geom_text(aes(label = as.character(round(cv0, 2)),
    #               x = cv0, 
    #               y = 1.2*ymax1),
    #           parse = TRUE) +          # add critical value
  labs(x = "t",
       y = "Density",
       title = expression(paste("     Distribution of test statistic under ", H[1]))) +
    xlim(c(xmin, xmax)) +
    theme(text = element_text(size = 16),
          axis.title.x = element_text(size = 20))
    
  h0 / h1
  
})

```




**Sample size calculator**
=====================================

Column {.sidebar}
-------------------------------------

We are testing 
<!--
$$
H_0: \mu = \mu_0 \enspace \mathrm{vs} \enspace H_1: \mu = \mu_1 > \mu_0.
$$
-->
$$
H_0: \mu = \mu_0
$$
against
$$
H_1: \mu = \mu_1 > \mu_0.
$$

<hr>


**Select population parameters:**


```{r h0.params2}

sliderInput("mu2", label = withMathJax("Null and alternative means \\( \\mu_0, \\mu_1 \\) \n
                                      Select \\( \\mu_0 < \\mu_1 \\):"),
            min = -2, max = 2, value = c(0, 1), step = 0.1)


sliderInput("sigma22", label = withMathJax('Variance \\( \\sigma^2 \\):'),
             min = 0, max = 10, value = 1, step = 0.1)
```

<hr>



**Select test settings:**


```{r h1.params2}



# sliderInput("mu12", label = withMathJax('Alternative mean \\( \\mu_1 \\):'),
#             min = 0, max = 2, value = 1, step = 0.1)

sliderInput("alpha2", label = withMathJax('Type I error rate \\( \\alpha \\):'),
            min = 0, max = 1, value = 0.05)




```




<hr>


The effect size $d = (\mu_1 - \mu_0) / \sigma$ is

```{r effect.size2}
  
renderPrint({
  # read inputs
  mu <- input$mu2
  mu0 <- mu[1]
  mu1 <- mu[2]
  sigma2 <- input$sigma22
  print(paste0("d = ", round((mu1 - mu0) / sqrt(sigma2), 2)))
})  

```





Column
-------------------------------------


###







```{r power.calculator}

fillCol(flex = c(NA, 1), 
  sliderInput(
    "power", label = "Desired power:",
            min = 0, max = 1, value = 0.8
    ),
  plotOutput("power_plot", height = "100%")
)


output$power_plot <- renderPlot({
  
  # read inputs
  mu <- input$mu2
  mu0 <- mu[1]
  mu1 <- mu[2]
  sigma2 <- input$sigma22
  power <- input$power
  
  t1e <- input$alpha2
  
  
  # create power function
  power_fun <- function(n){
    cv0 <- qt(1-t1e, df = n-1)
    tncp <- (mu1 - mu0) * sqrt(n / sigma2)
    pt(cv0, df = n-1, ncp = tncp, lower.tail = FALSE)
  } 
  
  # determine biggest n
  b_target <- max(power, 0.999)
  for(i in 2:5000){
    if(power_fun(i) > b_target) break
  }
  nmax <- i
  
  # determine solution
  for(i in 2:nmax){
    if(power_fun(i) > power) break
  }
  nstar <- i
  
  plot.title <- ifelse(nstar == nmax, paste("     Smallest possible sample size: >", nstar),
                       paste("     Smallest possible sample size:", nstar))
  
  # set y axis limits nmax and step size
  nmax <- min(nmax, 2*nstar)
  nmax <- ifelse(nmax > 49, 50*ceiling(nmax/50), nmax)
  stepsize <- max(round(nmax / 10), 1)
  
  # plot
  power_plot <- ggplot(tibble(n = 2:nmax, b = power_fun(2:nmax))) +
    geom_line(aes(x = n, y = b),
              size = 1) + # power function
    geom_segment(aes(x = nstar, xend = nstar,
                     y = 0, yend = power_fun(nstar)),
                 linetype="dashed",
                  size=0.5) + # nstar line
    geom_segment(aes(x = 0, xend = nstar,
                     y = power_fun(nstar), yend = power_fun(nstar)),
                 linetype="dashed",
                  size=0.5) + # power line
    labs(x = expression(paste("Sample size ", n)),
         y = "Power",
         title = plot.title) +
    theme(axis.text = element_text(size = 14),
          axis.title.x = element_text(size = 14)) +
    theme(text = element_text(size = 16),
          axis.title.x = element_text(size = 18),
          axis.title.y = element_text(size = 16)) +
    scale_x_continuous(breaks = function(x) seq(from = 0, to = floor(x[2]), by = stepsize)) +
    #scale_y_continuous(breaks = seq(from = 0, to = 1, by = 0.1)) +
    coord_flip()
  
  
  power_plot
  
})



```